
predict_one_hot_encoder <- function(object, newdata){
  # object: an object generated by the function "get_one_hot_encoder()"
  # newdata: a data frame of new observations
  
  output <- data.frame(predict(object = object, newdata = newdata))
  
  output
}


# # example 1
# 
# source("./src/get_one_hot_encoder.R")
# 
# data <- data.frame(id=c(10,20,30,40,50),
#                    gender=c('male','female','female','male','female'),
#                    mood=c('happy','sad','happy','sad','happy'),
#                    outcome=c(1,1,0,0,0))
# 
# str(data)
# 
# data_one_hot_encoder <- get_one_hot_encoder(data = data)
# 
# data_one_hot_encoder
# 
# result <- predict_one_hot_encoder(object = data_one_hot_encoder, newdata = data)
# 
# result
# 
# result <- predict_one_hot_encoder(object = data_one_hot_encoder, newdata = data[1, ])
# 
# result
