
predict_standard_scaler <- function(object, newdata){
  # object: an object generated by the function "get_standard_scaler()"
  # newdata: a data frame of new observations
  
  output <- predict(object = object, newdata = newdata)
  
  output
}


# # example 1
# 
# source("./src/get_standard_scaler.R")
# 
# data <- data.frame(cbind(1:10, 1:10))
# 
# data
# 
# data_scaler <- get_standard_scaler(data = data, method = c("center", "scale"))
# 
# newdata <- data[c(1, 2, 3, 8, 9, 10), ]
# 
# newdata
# 
# results <- predict_standard_scaler(object = data_scaler, newdata = newdata)
# 
# results
